on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - name: Get Release Info
        run: |
          echo "RELEASE_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          echo "OS_NAME=${{ matrix.goos }}" >> $GITHUB_ENV
      - name: Uppercase Darwin
        if: matrix.goos == 'darwin'
        run: echo "OS_NAME=Darwin" >> $GITHUB_ENV
      - name: Uppercase Linux
        if: matrix.goos == 'linux'
        run: echo "OS_NAME=Linux" >> $GITHUB_ENV
      - name: Uppercase Windows
        if: matrix.goos == 'windows'
        run: echo "OS_NAME=Win" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.34
        with:
          md5sum: false
          extra_files: README.md LICENSE env.example
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goversion: "https://dl.google.com/go/go1.19.3.linux-amd64.tar.gz"
          asset_name: "${{ env.REPOSITORY_NAME }}-${{ env.OS_NAME }}-${{ matrix.goarch }}"

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:latest
